### ISSUE TITLE
Webrtc-vad is missing

### ISSUE THREAD

**Issue by vergnu** [denoming/esp32-i2s-mic-vad#1]
Hello, denoming.   
The webpage after the webrtc-vad link in the components folder of this project is missing. After downloading the file, the webrtc-vad file is empty. May I ask if this will have an impact on subsequent co
![1](https://github.com/denoming/esp32-i2s-mic-vad/assets/157200317/c7df3283-decb-4bcd-94cd-5c14b6318118)
![2](https://github.com/denoming/esp32-i2s-mic-vad/assets/157200317/1a3916f1-91a6-4f62-b783-4b69b067e33b)
mpilation.

**Comment by denoming** [comment]
Hello, fixed. Pull the last update and follow instructions in README.md file.

**Comment by vergnu** [comment]
Thank you for your update!
